# Dockerfile para MySQL

# Usa una imagen base de MySQL
FROM mysql:latest

# Expone el puerto 3306
EXPOSE 3306

# Define las variables de entorno para la configuración de MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=app_database
